// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace aspnetserver.Models;

public partial class SavedAsset
{
    public int AssetId { get; set; }

    public int OwnerUserId { get; set; }

    public string SavedAsset1 { get; set; }

    public DateTime CreatedAt { get; set; }

    public string FileName { get; set; }

    public virtual User OwnerUser { get; set; }

    public virtual ICollection<UserFavorite> UserFavorites { get; set; } = new List<UserFavorite>();
}