// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace aspnetserver.Models;

public partial class UserFavorite
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int AssetId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual SavedAsset Asset { get; set; }

    public virtual User User { get; set; }
}